export const practiceData = [
  {
    "title": "Software Engineer",
    "companyName": "TechCorp",
    "companyLink": "https://techcorp.com",
    "jobType": "Full-time",
    "responsibilities": [
      "Develop and maintain web applications",
      "Collaborate with cross-functional teams",
      "Write clean and efficient code"
    ],
    "skills": ["JavaScript", "React", "Node.js", "PostgreSQL"],
    "tags": ["Software Engineering", "Web Development", "Full-time"],
    "benefits": ["Health Insurance", "Remote Work", "Stock Options"],
    "currency": "USD",
    "salaryFrequency": "Monthly",
    "minSalary": 6000,
    "maxSalary": 9000,
    "remote": true,
    "location": "San Francisco, CA",
    "description": "We are looking for a skilled Software Engineer to build scalable web applications.",
    "insights": "Competitive salary and flexible working hours.",
    "link": "https://techcorp.com/jobs/software-engineer",
    "applyLink": "https://techcorp.com/apply/software-engineer",
    "applyBy": new Date("2025-04-15T00:00:00.000Z"),
    "postedAt": new Date("2025-03-10T00:00:00.000Z")
  },
  {
    "title": "Data Scientist",
    "companyName": "DataGen AI",
    "companyLink": "https://datagen.ai",
    "jobType": "Contract",
    "responsibilities": [
      "Analyze large datasets for insights",
      "Develop machine learning models",
      "Work closely with engineers and analysts"
    ],
    "skills": ["Python", "TensorFlow", "SQL", "Data Visualization"],
    "tags": ["Data Science", "AI", "Contract"],
    "benefits": ["Flexible hours", "Remote work"],
    "currency": "USD",
    "salaryFrequency": "Hourly",
    "minSalary": 50,
    "maxSalary": 80,
    "remote": true,
    "location": "Remote",
    "description": "Join our AI-driven team to analyze big data and build predictive models.",
    "insights": "Opportunity to work on cutting-edge AI projects.",
    "link": "https://datagen.ai/jobs/data-scientist",
    "applyLink": "https://datagen.ai/apply/data-scientist",
    "applyBy": new Date("2025-04-20T00:00:00.000Z"),
    "postedAt": new Date("2025-03-12T00:00:00.000Z")
  },
  {
    "title": "Product Manager",
    "companyName": "InnovateX",
    "companyLink": "https://innovatex.com",
    "jobType": "Full-time",
    "responsibilities": [
      "Define product strategy and roadmap",
      "Coordinate with engineering and marketing teams",
      "Gather user feedback to improve products"
    ],
    "skills": ["Product Management", "Agile", "Leadership"],
    "tags": ["Product Management", "Strategy", "Full-time"],
    "benefits": ["Health Insurance", "Stock Options", "Paid Time Off"],
    "currency": "USD",
    "salaryFrequency": "Annual",
    "minSalary": 90000,
    "maxSalary": 120000,
    "remote": false,
    "location": "New York, NY",
    "description": "We are seeking an experienced Product Manager to drive product strategy.",
    "insights": "Fast-paced environment with high growth opportunities.",
    "link": "https://innovatex.com/jobs/product-manager",
    "applyLink": "https://innovatex.com/apply/product-manager",
    "applyBy": new Date("2025-04-25T00:00:00.000Z"),
    "postedAt": new Date("2025-03-14T00:00:00.000Z")
  },
  {
    "title": "Frontend Developer",
    "companyName": "WebWorks",
    "companyLink": "https://webworks.io",
    "jobType": "Full-time",
    "responsibilities": [
      "Develop responsive user interfaces",
      "Optimize applications for speed and scalability",
      "Work closely with UX designers"
    ],
    "skills": ["HTML", "CSS", "JavaScript", "React", "TypeScript"],
    "tags": ["Frontend", "Web Development", "React"],
    "benefits": ["Health Insurance", "Remote Work", "Flexible Hours"],
    "currency": "USD",
    "salaryFrequency": "Monthly",
    "minSalary": 5000,
    "maxSalary": 8000,
    "remote": true,
    "location": "Los Angeles, CA",
    "description": "Join our team as a Frontend Developer to create amazing web experiences.",
    "insights": "Modern tech stack and a fun work environment.",
    "link": "https://webworks.io/jobs/frontend-developer",
    "applyLink": "https://webworks.io/apply/frontend-developer",
    "applyBy": new Date("2025-04-30T00:00:00.000Z"),
    "postedAt": new Date("2025-03-16T00:00:00.000Z")
  },
  {
    "title": "Backend Engineer",
    "companyName": "CloudX Solutions",
    "companyLink": "https://cloudx.com",
    "jobType": "Full-time",
    "responsibilities": [
      "Develop and maintain scalable APIs",
      "Ensure system reliability and security",
      "Optimize database performance"
    ],
    "skills": ["Node.js", "Express", "MongoDB", "Docker", "AWS"],
    "tags": ["Backend", "API Development", "Full-time"],
    "benefits": ["Remote Work", "Stock Options", "Flexible Schedule"],
    "currency": "USD",
    "salaryFrequency": "Monthly",
    "minSalary": 7000,
    "maxSalary": 10000,
    "remote": true,
    "location": "Remote",
    "description": "We are hiring a Backend Engineer to build robust and scalable APIs.",
    "insights": "Opportunity to work with cutting-edge cloud technologies.",
    "link": "https://cloudx.com/jobs/backend-engineer",
    "applyLink": "https://cloudx.com/apply/backend-engineer",
    "applyBy": new Date("2025-05-05T00:00:00.000Z"),
    "postedAt": new Date("2025-03-18T00:00:00.000Z")
  },
  {
    "title": "DevOps Engineer",
    "companyName": "OpsGenius",
    "companyLink": "https://opsgenius.dev",
    "jobType": "Full-time",
    "responsibilities": [
      "Automate infrastructure deployment",
      "Monitor system performance and availability",
      "Enhance CI/CD pipelines"
    ],
    "skills": ["Kubernetes", "Docker", "Terraform", "AWS", "CI/CD"],
    "tags": ["DevOps", "Cloud", "Infrastructure"],
    "benefits": ["Health Insurance", "Remote Work", "Paid Time Off"],
    "currency": "USD",
    "salaryFrequency": "Annual",
    "minSalary": 100000,
    "maxSalary": 130000,
    "remote": true,
    "location": "Seattle, WA",
    "description": "We need an experienced DevOps Engineer to manage and optimize our infrastructure.",
    "insights": "Collaborate with top engineers in the field.",
    "link": "https://opsgenius.dev/jobs/devops-engineer",
    "applyLink": "https://opsgenius.dev/apply/devops-engineer",
    "applyBy": new Date("2025-05-10T00:00:00.000Z"),
    "postedAt": new Date("2025-03-20T00:00:00.000Z")
  },
  {
    "title": "Cybersecurity Analyst",
    "companyName": "SecureTech",
    "companyLink": "https://securetech.io",
    "jobType": "Full-time",
    "responsibilities": [
      "Monitor and analyze security threats",
      "Implement security measures and policies",
      "Respond to security incidents"
    ],
    "skills": ["Cybersecurity", "SIEM", "Incident Response", "Python"],
    "tags": ["Cybersecurity", "Security Analyst", "Infosec"],
    "benefits": ["Health Insurance", "401(k)", "Remote Work"],
    "currency": "USD",
    "salaryFrequency": "Annual",
    "minSalary": 90000,
    "maxSalary": 120000,
    "remote": false,
    "location": "Austin, TX",
    "description": "Join SecureTech to protect digital assets and ensure security compliance.",
    "insights": "Great learning opportunities and career growth.",
    "link": "https://securetech.io/jobs/cybersecurity-analyst",
    "applyLink": "https://securetech.io/apply/cybersecurity-analyst",
    "applyBy": new Date("2025-05-15T00:00:00.000Z"),
    "postedAt": new Date("2025-03-22T00:00:00.000Z")
  },
  {
    "title": "UX Designer",
    "companyName": "DesignStudio",
    "companyLink": "https://designstudio.com",
    "jobType": "Part-time",
    "responsibilities": [
      "Design user-friendly interfaces",
      "Conduct user research and testing",
      "Collaborate with developers and product teams"
    ],
    "skills": ["UI/UX Design", "Figma", "User Research", "Prototyping"],
    "tags": ["UX Design", "Product Design", "Part-time"],
    "benefits": ["Remote Work", "Flexible Hours"],
    "currency": "USD",
    "salaryFrequency": "Hourly",
    "minSalary": 40,
    "maxSalary": 70,
    "remote": true,
    "location": "Remote",
    "description": "We are looking for a creative UX Designer to enhance our product experiences.",
    "insights": "Work with innovative startups on exciting design projects.",
    "link": "https://designstudio.com/jobs/ux-designer",
    "applyLink": "https://designstudio.com/apply/ux-designer",
    "applyBy": new Date("2025-05-20T00:00:00.000Z"),
    "postedAt": new Date("2025-03-24T00:00:00.000Z")
  },
  {
    "title": "QA Engineer",
    "companyName": "TestMasters",
    "companyLink": "https://testmasters.dev",
    "jobType": "Full-time",
    "responsibilities": [
      "Develop test plans and cases",
      "Automate testing processes",
      "Identify and report bugs"
    ],
    "skills": ["Quality Assurance", "Test Automation", "Bug Tracking", "Selenium"],
    "tags": ["QA", "Testing", "Quality Assurance"],
    "benefits": ["Health Insurance", "Remote Work", "Paid Time Off"],
    "currency": "USD",
    "salaryFrequency": "Monthly",
    "minSalary": 5000,
    "maxSalary": 8000,
    "remote": true,
    "location": "San Diego, CA",
    "description": "We are hiring a QA Engineer to ensure the quality of our software products.",
    "insights": "Opportunity to work on diverse projects and cutting-edge tools.",
    "link": "https://testmasters.dev/jobs/qa-engineer",
    "applyLink": "https://testmasters.dev/apply/qa-engineer",
    "applyBy": new Date("2025-05-25T00:00:00.000Z"),
    "postedAt": new Date("2025-03-26T00:00:00.000Z")
  },
  {
    "title": "Technical Writer",
    "companyName": "WriteTech",
    "companyLink": "https://writetech.io",
    "jobType": "Contract",
    "responsibilities": [
      "Create technical documentation and guides",
      "Edit and proofread content",
      "Collaborate with engineers and product teams"
    ],
    "skills": ["Technical Writing", "Editing", "Documentation", "APIs"],
    "tags": ["Technical Writing", "Documentation", "Contract"],
    "benefits": ["Flexible Hours", "Remote Work"],
    "currency": "USD",
    "salaryFrequency": "Hourly",
    "minSalary": 30,
    "maxSalary": 50,
    "remote": true,
    "location": "Remote",
    "description": "Join WriteTech as a Technical Writer to create clear and concise technical content.",
    "insights": "Work on exciting projects and collaborate with top tech teams.",
    "link": "https://writetech.io/jobs/technical-writer",
    "applyLink": "https://writetech.io/apply/technical-writer",
    "applyBy": new Date("2025-05-30T00:00:00.000Z"),
    "postedAt": new Date("2025-03-28T00:00:00.000Z")
  },
  {
    "title": "Software Engineer",
    "companyName": "TechCorp",
    "companyLink": "https://techcorp.com",
    "jobType": "Full-time",
    "responsibilities": [
      "Develop and maintain web applications",
      "Collaborate with cross-functional teams",
      "Write clean and efficient code"
    ],
    "skills": ["JavaScript", "React", "Node.js", "PostgreSQL"],
    "tags": ["Software Engineering", "Web Development", "Full-time"],
    "description": "We are looking for a skilled Software Engineer to build scalable web applications.",
    "insights": "Competitive salary and flexible working hours.",
    "link": "https://techcorp.com/jobs/software-engineer",
    "applyLink": "https://techcorp.com/apply/software-engineer",
    "applyBy": new Date("2025-04-15T00:00:00.000Z"),
    "postedAt": new Date("2025-03-10T00:00:00.000Z")
  },
  {
    "title": "Full Stack Developer",
    "companyName": "CodeGenius",
    "companyLink": "https://codegenius.dev",
    "jobType": "Full-time",
    "responsibilities": [
      "Develop front-end and back-end applications",
      "Ensure high performance and scalability",
      "Write clean and maintainable code"
    ],
    "skills": ["JavaScript", "React", "Node.js", "MongoDB"],
    "tags": ["Software Engineering", "Full Stack", "Full-time"],
    "description": "Join us as a Full Stack Developer to work on innovative software solutions.",
    "insights": "Opportunity to learn and grow with a talented team.",
    "link": "https://codegenius.dev/jobs/full-stack-developer",
    "applyLink": "https://codegenius.dev/apply/full-stack-developer",
    "applyBy": new Date("2025-04-18T00:00:00.000Z"),
    "postedAt": new Date("2025-03-12T00:00:00.000Z")
  },
  {
    "title": "Frontend Engineer",
    "companyName": "WebWorks",
    "companyLink": "https://webworks.io",
    "jobType": "Full-time",
    "responsibilities": [
      "Develop responsive user interfaces",
      "Optimize applications for speed and scalability",
      "Work closely with UX designers"
    ],
    "skills": ["HTML", "CSS", "JavaScript", "React", "TypeScript"],
    "tags": ["Frontend", "Web Development", "React"],
    "description": "Join our team as a Frontend Engineer to create amazing web experiences.",
    "insights": "Modern tech stack and a fun work environment.",
    "link": "https://webworks.io/jobs/frontend-engineer",
    "applyLink": "https://webworks.io/apply/frontend-engineer",
    "applyBy": new Date("2025-04-20T00:00:00.000Z"),
    "postedAt": new Date("2025-03-14T00:00:00.000Z")
  },
  {
    "title": "Backend Engineer",
    "companyName": "CloudX Solutions",
    "companyLink": "https://cloudx.com",
    "jobType": "Full-time",
    "responsibilities": [
      "Develop and maintain scalable APIs",
      "Ensure system reliability and security",
      "Optimize database performance"
    ],
    "skills": ["Node.js", "Express", "PostgreSQL", "Docker", "AWS"],
    "tags": ["Backend", "API Development", "Full-time"],
    "description": "We are hiring a Backend Engineer to build robust and scalable APIs.",
    "insights": "Opportunity to work with cutting-edge cloud technologies.",
    "link": "https://cloudx.com/jobs/backend-engineer",
    "applyLink": "https://cloudx.com/apply/backend-engineer",
    "applyBy": new Date("2025-04-25T00:00:00.000Z"),
    "postedAt": new Date("2025-03-16T00:00:00.000Z")
  },
  {
    "title": "Machine Learning Engineer",
    "companyName": "AI Innovators",
    "companyLink": "https://aiinnovators.com",
    "jobType": "Full-time",
    "responsibilities": [
      "Build and deploy machine learning models",
      "Optimize AI algorithms for performance",
      "Collaborate with data scientists and engineers"
    ],
    "skills": ["Python", "TensorFlow", "PyTorch", "ML Ops"],
    "tags": ["Machine Learning", "AI", "Full-time"],
    "description": "We are looking for a Machine Learning Engineer to develop AI-driven applications.",
    "insights": "Work on cutting-edge AI projects with a talented team.",
    "link": "https://aiinnovators.com/jobs/machine-learning-engineer",
    "applyLink": "https://aiinnovators.com/apply/machine-learning-engineer",
    "applyBy": new Date("2025-04-30T00:00:00.000Z"),
    "postedAt": new Date("2025-03-18T00:00:00.000Z")
  }
]
